title: Chicago DSA
description: The official website of the Chicago chapter of the Democratic Socialists of America.
chapter:
  name: Chicago DSA
  url:
  facebook: https://www.facebook.com/ChicagoDemSocialists/
  instagram: https://www.instagram.com/chicagodsa/
  twitter: https://twitter.com/ChicagoCityDSA
custom-join: join
google_analytics:
teamup: "cb7ef970fd2b7b1a85acd5a8a2ef6d7f77477648b0963c29c629391742f24c5a"
permalink: pretty
remote_theme: ChicagoDSA/haymarket@v1.3.8

# Leave empty to disable
banner:
  text: "**Here's a banner:** you can turn it off/on, add styling, and link to other pages"
  link: another-page

defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: "assets/images/og-image.png"

# Add collections here
# https://jekyllrb.com/docs/collections/
collections:
  campaigns:
    output: true
  working-groups:
    output: true
