title: Chicago DSA
description: The official website of the Chicago chapter of the Democratic Socialists of America.
chapter:
  name: Chicago DSA
  url:
  facebook: https://www.facebook.com/ChicagoDemSocialists/
  instagram: https://www.instagram.com/chicagodsa/
  twitter: https://twitter.com/ChicagoCityDSA
  # Override DSA national logos
  header-logo-svg: "images/CDSA-logo-color.svg"
  header-logo-png-fallback: "images/CDSA-logo-color.png" # 360px square recommended
  background-logo-svg: "images/CDSA-logo-reverse.svg"
  background-logo-png-fallback: "images/CDSA-logo-reverse.png" # 1440px square recommended
  # Alt text for screen readers
  logo-description: A CTA train and the Sears Tower are in front of a rose.
custom-join: join
google_analytics:
teamup: "cb7ef970fd2b7b1a85acd5a8a2ef6d7f77477648b0963c29c629391742f24c5a"
permalink: pretty
remote_theme: ChicagoDSA/haymarket@v1.5.2

# Leave empty to disable
banner:
  text: "**Defund CPD endorsed:** read the Executive Committee's statement"
  link: another-page

defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: "assets/images/og-image.png"

# Add collections here
# https://jekyllrb.com/docs/collections/
collections:
  campaigns:
    output: true
  working-groups:
    output: true
